### ISSUE TITLE
useAzBicep temporarily broke due to Bicep (via `az bicep`) being b0rked in 2.46.0

### ISSUE THREAD

**Issue by spoelstraethan** [sam-cogan/arm-ttk-extension-xplatform#22]
It was noted here.
https://github.com/Azure/azure-cli/issues/25710

The fix was mentioned as potentially coming in with this PR scheduled for deployment today, but if your `useAzBicep` doesn't pull the latest version then it might still fail with the error mentioned above (and an example below).
https://github.com/Azure/azure-cli/pull/25729#issuecomment-1488501987

```
Using executable 'pwsh'
pwsh ps-runner.ps1 -templateLocation AzureResources\* -resultLocation TestResults -skipTests <snipped> `
 -mainTemplates main.bicep -cliOutputResults -ignoreExitCode -recurse -useAzBicep
##[error]ERROR: The command failed with an unexpected error. Here is the traceback:
ERROR: No section: 'bicep'
Traceback (most recent call last):
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/cli.py", line 233, in invoke
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 663, in execute
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 697, in _run_job
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/__init__.py", line 333, in __call__
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/core/commands/command_operation.py", line 121, in handler
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/custom.py", line 3671, in build_bicep_file
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 85, in run_bicep_command
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\azure/cli/command_modules/resource/_bicep.py", line 141, in ensure_bicep_installation
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 99, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 94, in get
  File "D:\a\_work\1\s\build_scripts\windows\artifacts\cli\Lib\site-packages\knack/config.py", line 208, in get
  File "configparser.py", line 783, in get
  File "configparser.py", line 1154, in _unify_values
configparser.NoSectionError: No section: 'bicep'

```

**Comment by sam-cogan** [comment]
The useAzBicep property just tells the plug-in to use the existing Az CLI installed on the system, it doesn't install or update it. It's up to the user to ensure there is a valid install of the Az CLI on the system.

**Comment by spoelstraethan** [comment]
I think the new version of Az CLI that fixes the missing default value for this has been released, so I'll consider the matter resolved and if anybody finds this via search, they can see it and know they need to update their Azure CLI.
